
name: Hexo Deploy

on:
  push:
    branches: ["develop"]

env:
  oauth_client_secret: ${{ vars.OAUTH_CLIENT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install hexo-cli -g

    - name: Install dependencies
      run: |
        npm install

    - name: Generate
      environment: github-pages
      run: |
        echo "oauth_client_secret: ${{ env.oauth_client_secret }}"
        touch db.json && hexo generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: master

